const cypherhausColor = "#2c4745";

export const stringStyle = {
  lineNumberColor: `white`,
  lineNumberBgColor: `white`,
  backgroundColor: cypherhausColor,
  textColor: `white`,
  substringColor: cypherhausColor,
  keywordColor: undefined,
  attributeColor: cypherhausColor,
  selectorAttributeColor: undefined,
  docTagColor: undefined,
  nameColor: `white`,
  builtInColor: `white`,
  literalColor: `white`,
  bulletColor: `white`,
  codeColor: `white`,
  additionColor: `white`,
  regexpColor: `white`,
  symbolColor: `white`,
  variableColor: `white`,
  templateVariableColor: `white`,
  linkColor: `white`,
  selectorClassColor: `white`,
  typeColor: `white`,
  stringColor: cypherhausColor,
  selectorIdColor: `white`,
  quoteColor: `white`,
  templateTagColor: `white`,
  deletionColor: `white`,
  titleColor: `white`,
  sectionColor: cypherhausColor,
  commentColor: `white`,
  metaKeywordColor: `white`,
  metaColor: `white`,
  functionColor: `white`,
  numberColor: `white`,
};

export const cyhperhausStyle = {
  lineNumberColor: cypherhausColor,
  lineNumberBgColor: `white`,
  backgroundColor: `white`,
  textColor: `black`,
  substringColor: cypherhausColor,
  keywordColor: undefined,
  attributeColor: cypherhausColor,
  selectorAttributeColor: undefined,
  docTagColor: undefined,
  nameColor: cypherhausColor,
  builtInColor: cypherhausColor,
  literalColor: cypherhausColor,
  bulletColor: cypherhausColor,
  codeColor: cypherhausColor,
  additionColor: cypherhausColor,
  regexpColor: cypherhausColor,
  symbolColor: cypherhausColor,
  variableColor: cypherhausColor,
  templateVariableColor: cypherhausColor,
  linkColor: cypherhausColor,
  selectorClassColor: `#0048ab`,
  typeColor: cypherhausColor,
  stringColor: cypherhausColor,
  selectorIdColor: `#0048ab`,
  quoteColor: `#0048ab`,
  templateTagColor: `#00193a`,
  deletionColor: `#4c81c9`,
  titleColor: `#0048ab`,
  sectionColor: cypherhausColor,
  commentColor: `#738191`,
  metaKeywordColor: cypherhausColor,
  metaColor: cypherhausColor,
  functionColor: cypherhausColor,
  numberColor: cypherhausColor,
};
