import type { NextPage } from "next";
import Head from "next/head";
import { Foss } from "../components/Foss";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CYPHERHAUS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span className="tracking-wide font-display tracking-widest text-3xl">
        CYPHERHAUS
      </span>
      <main>
        <Foss />
      </main>
    </div>
  );
};

export default Home;
