import type { NextPage } from "next";
import Head from "next/head";
import { Logo } from "../components/Logo";
import { Card } from "../components/common/Card";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CYPHERHAUS</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className="pt-8 pb-4 flex justify-center mb-6">
        <Logo />
      </header>
      <main>
        <div className="flex w-full justify-center pt-8">
          <Card
            title="LSD"
            description="Lightning and Supabase Demo using ZBD's API."
            link="/blog/lsd"
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
